#!/usr/bin/env python


#    Copyright Paul Munday 2013

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# MAIN

if __name__ == "__main__": 
    # pass
    #initialisation
    parser=argparse.ArgumentParser()
    parser.add_argument("--test", help="Run specified test. See README.tests")
    parser.add_argument("--pos", help="specify the serial port the pos is connected to. e.g. /dev/pts/11")
    parser.add_argument("--scale", help="specify the serial port the scale is connected to. e.g. /dev/ttyS3")
    args=parser.parse_args()
    if args.test:
        if args.test == 'samsung':
            pos_test_samsung(args.pos)
        elif args.test == 'dialog':
            pos_test_dialog(args.pos)

