#!/usr/bin/env python


#    Copyright Paul Munday 2013

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import argparse
import swrapper         # this programs module
from swrapper import get_config
from swrapper import pos_test_samsung, pos_test_dialog, scale_test_magellan
# MAIN

if __name__ == "__main__": 
    
    #read command line arguments
    parser=argparse.ArgumentParser()
    parser.add_argument("--test", choices=['samsung', 'dialog', 'magellan'], help="Run specified test. See README.tests")
    parser.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")
    parser.add_argument("--pos", help="specify the scale type used by the POS. Once of dialog or samsung. If not specified the program will attempt to use scale type defined in the config file.")
    parser.add_argument("--scale", help="specify scale that is connected. Possible values include dummy, MagellanSASI, PC-100. If not specified the program will attempt to use a scale defined in the config file.")
    parser.add_argument("--pos-serial", help="specify the serial port the pos is connected to. e.g. /dev/pts/11")
    parser.add_argument("--scale-serial", help="specify the serial port the scale is connected to. e.g. /dev/ttyS3")
    args=parser.parse_args()

    # run tests
    if args.test:
        if args.test == 'samsung':
            pos_test_samsung(args.pos-serial)
        elif args.test == 'dialog':
            pos_test_dialog(args.pos-serial)
        elif args.test == 'magellan':
            scale_test_magellan(args.scale-serial)
        print('completed tests')
        sys.exit(0)


    # read config file
    pos_config = get_config('pos')
    scale_config = get_config('scale')
    defined_scale = get_config('scale_definition')

    if args.pos:
        pos_scale = args.pos
    elif pos_config['scale']:
        pos_scale = pos_config['scale']
    else:
        pos_scale = 'samsung'

    try:
        if args.scale:
            external_scale = args.scale
        elif scale_config['type']:
             external_scale = scale_config['type']
    except:
        print('No external scale defined')
        raise NameError

    try:
        if args.scale-serial:
            external_scale_serialport = args.scale-serial
        elif scale_config['serialport']:
            external_scale_serialport = scale_config['serialport']
    except:
        print('No serial port defined for external scale:' + external_scale)
        raise NameError


